// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// $Rev: 98350 $
// File generated on 29.05.2022 15:36:41 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files (x86)\Embarcadero\Studio\21.0\bin\Borland.Studio.ToolsAPI.tlb (1)
// LIBID: {718062B4-5EB5-4171-AB94-80108322C37E}
// LCID: 0
// Helpfile: 
// HelpString: Embarcadero RAD Studio ToolsAPI Assembly
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
//   (2) v2.4 mscorlib, (C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.tlb)
//   (3) v2.0 System, (C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\System.tlb)
//   (4) v2.0 System_Windows_Forms, (C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\System.Windows.Forms.tlb)
//   (5) v2.0 System_Drawing, (C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\System.Drawing.tlb)
// SYS_KIND: SYS_WIN32
// ************************************************************************ //
#ifndef   Borland_Studio_ToolsAPI_OCXH
#define   Borland_Studio_ToolsAPI_OCXH

#pragma option push -b -w-inl -w-8118
#pragma pack(push, 4)

#include <Vcl.OleCtrls.hpp>
#include <Vcl.OleServer.hpp>
#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <System.Win.StdVCL.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "mscorlib_TLB.h"
#include "System_TLB.h"
#include "System_Windows_Forms_TLB.h"
#include "System_Drawing_TLB.h"

#include "Borland_Studio_ToolsAPI_TLB.h"
namespace Borland_studio_toolsapi_tlb
{

// *********************************************************************//
// HelpString: Embarcadero RAD Studio ToolsAPI Assembly
// Version:    27.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TBorlandIDE
// Help String      : 
// Default Interface: _Object
// Def. Intf. Object: _ObjectPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TBorlandIDE : public Vcl::Oleserver::TOleServer
{
  _ObjectPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TBorlandIDE(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ObjectPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ObjectPtr intf);


  BSTR            __fastcall get_ToString(void);
  VARIANT_BOOL    __fastcall Equals(VARIANT obj/*[in]*/);
  long            __fastcall GetHashCode(void);
  Mscorlib_tlb::_Type* __fastcall GetType(void);
  __property BSTR ToString={ read=get_ToString };
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TCodeUpdater
// Help String      : 
// Default Interface: _CodeUpdater
// Def. Intf. Object: _CodeUpdaterPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TCodeUpdater : public Vcl::Oleserver::TOleServer
{
  _CodeUpdaterPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TCodeUpdater(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _CodeUpdaterPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_CodeUpdaterPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TStringCollectionAdapter
// Help String      : 
// Default Interface: _StringCollectionAdapter
// Def. Intf. Object: _StringCollectionAdapterPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TStringCollectionAdapter : public Vcl::Oleserver::TOleServer
{
  _StringCollectionAdapterPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TStringCollectionAdapter(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _StringCollectionAdapterPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_StringCollectionAdapterPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TDocumentationManager
// Help String      : 
// Default Interface: _DocumentationManager
// Def. Intf. Object: _DocumentationManagerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TDocumentationManager : public Vcl::Oleserver::TOleServer
{
  _DocumentationManagerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TDocumentationManager(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _DocumentationManagerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_DocumentationManagerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRefactoringException
// Help String      : 
// Default Interface: _RefactoringException
// Def. Intf. Object: _RefactoringExceptionPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TRefactoringException : public Vcl::Oleserver::TOleServer
{
  _RefactoringExceptionPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRefactoringException(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _RefactoringExceptionPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_RefactoringExceptionPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRefactoringKinds
// Help String      : 
// Default Interface: _RefactoringKinds
// Def. Intf. Object: _RefactoringKindsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TRefactoringKinds : public Vcl::Oleserver::TOleServer
{
  _RefactoringKindsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRefactoringKinds(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _RefactoringKindsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_RefactoringKindsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRefactoringHelpContextIds
// Help String      : 
// Default Interface: _RefactoringHelpContextIds
// Def. Intf. Object: _RefactoringHelpContextIdsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TRefactoringHelpContextIds : public Vcl::Oleserver::TOleServer
{
  _RefactoringHelpContextIdsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRefactoringHelpContextIds(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _RefactoringHelpContextIdsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_RefactoringHelpContextIdsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRefactoringEventArgs
// Help String      : 
// Default Interface: _RefactoringEventArgs
// Def. Intf. Object: _RefactoringEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TRefactoringEventArgs : public Vcl::Oleserver::TOleServer
{
  _RefactoringEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRefactoringEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _RefactoringEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_RefactoringEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRefactoringEvent
// Help String      : 
// Default Interface: _RefactoringEvent
// Def. Intf. Object: _RefactoringEventPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TRefactoringEvent : public Vcl::Oleserver::TOleServer
{
  _RefactoringEventPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRefactoringEvent(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _RefactoringEventPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_RefactoringEventPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRefactoringRegistrarEventHandler
// Help String      : 
// Default Interface: _RefactoringRegistrarEventHandler
// Def. Intf. Object: _RefactoringRegistrarEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TRefactoringRegistrarEventHandler : public Vcl::Oleserver::TOleServer
{
  _RefactoringRegistrarEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRefactoringRegistrarEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _RefactoringRegistrarEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_RefactoringRegistrarEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TPlatforms
// Help String      : 
// Default Interface: _Platforms
// Def. Intf. Object: _PlatformsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TPlatforms : public Vcl::Oleserver::TOleServer
{
  _PlatformsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TPlatforms(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _PlatformsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_PlatformsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTAEditorFileTypes
// Help String      : 
// Default Interface: _OTAEditorFileTypes
// Def. Intf. Object: _OTAEditorFileTypesPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTAEditorFileTypes : public Vcl::Oleserver::TOleServer
{
  _OTAEditorFileTypesPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTAEditorFileTypes(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTAEditorFileTypesPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTAEditorFileTypesPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TViewActivatedEventArgs
// Help String      : 
// Default Interface: _ViewActivatedEventArgs
// Def. Intf. Object: _ViewActivatedEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TViewActivatedEventArgs : public Vcl::Oleserver::TOleServer
{
  _ViewActivatedEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TViewActivatedEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ViewActivatedEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ViewActivatedEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TViewNotificationEventArgs
// Help String      : 
// Default Interface: _ViewNotificationEventArgs
// Def. Intf. Object: _ViewNotificationEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TViewNotificationEventArgs : public Vcl::Oleserver::TOleServer
{
  _ViewNotificationEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TViewNotificationEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ViewNotificationEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ViewNotificationEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TViewActivatedEventHandler
// Help String      : 
// Default Interface: _ViewActivatedEventHandler
// Def. Intf. Object: _ViewActivatedEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TViewActivatedEventHandler : public Vcl::Oleserver::TOleServer
{
  _ViewActivatedEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TViewActivatedEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ViewActivatedEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ViewActivatedEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TViewNotificationEventHandler
// Help String      : 
// Default Interface: _ViewNotificationEventHandler
// Def. Intf. Object: _ViewNotificationEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TViewNotificationEventHandler : public Vcl::Oleserver::TOleServer
{
  _ViewNotificationEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TViewNotificationEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ViewNotificationEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ViewNotificationEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRenameNotificationEventArgs
// Help String      : 
// Default Interface: _RenameNotificationEventArgs
// Def. Intf. Object: _RenameNotificationEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TRenameNotificationEventArgs : public Vcl::Oleserver::TOleServer
{
  _RenameNotificationEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRenameNotificationEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _RenameNotificationEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_RenameNotificationEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRenameNotificationEventHandler
// Help String      : 
// Default Interface: _RenameNotificationEventHandler
// Def. Intf. Object: _RenameNotificationEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TRenameNotificationEventHandler : public Vcl::Oleserver::TOleServer
{
  _RenameNotificationEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRenameNotificationEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _RenameNotificationEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_RenameNotificationEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TModuleAddedRemovedEventArgs
// Help String      : 
// Default Interface: _ModuleAddedRemovedEventArgs
// Def. Intf. Object: _ModuleAddedRemovedEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TModuleAddedRemovedEventArgs : public Vcl::Oleserver::TOleServer
{
  _ModuleAddedRemovedEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TModuleAddedRemovedEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ModuleAddedRemovedEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ModuleAddedRemovedEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TModuleRenamedEventArgs
// Help String      : 
// Default Interface: _ModuleRenamedEventArgs
// Def. Intf. Object: _ModuleRenamedEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TModuleRenamedEventArgs : public Vcl::Oleserver::TOleServer
{
  _ModuleRenamedEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TModuleRenamedEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ModuleRenamedEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ModuleRenamedEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TModuleAddedRemovedEventHandler
// Help String      : 
// Default Interface: _ModuleAddedRemovedEventHandler
// Def. Intf. Object: _ModuleAddedRemovedEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TModuleAddedRemovedEventHandler : public Vcl::Oleserver::TOleServer
{
  _ModuleAddedRemovedEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TModuleAddedRemovedEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ModuleAddedRemovedEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ModuleAddedRemovedEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TModuleRenamedEventHandler
// Help String      : 
// Default Interface: _ModuleRenamedEventHandler
// Def. Intf. Object: _ModuleRenamedEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TModuleRenamedEventHandler : public Vcl::Oleserver::TOleServer
{
  _ModuleRenamedEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TModuleRenamedEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ModuleRenamedEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ModuleRenamedEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TToolboxItemEventArgs
// Help String      : 
// Default Interface: _ToolboxItemEventArgs
// Def. Intf. Object: _ToolboxItemEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TToolboxItemEventArgs : public Vcl::Oleserver::TOleServer
{
  _ToolboxItemEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TToolboxItemEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ToolboxItemEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ToolboxItemEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TToolboxItemAddedEventArgs
// Help String      : 
// Default Interface: _ToolboxItemAddedEventArgs
// Def. Intf. Object: _ToolboxItemAddedEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TToolboxItemAddedEventArgs : public Vcl::Oleserver::TOleServer
{
  _ToolboxItemAddedEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TToolboxItemAddedEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ToolboxItemAddedEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ToolboxItemAddedEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TTOTAHandle
// Help String      : 
// Default Interface: _TOTAHandle
// Def. Intf. Object: _TOTAHandlePtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TTOTAHandle : public Vcl::Oleserver::TOleServer
{
  _TOTAHandlePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TTOTAHandle(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _TOTAHandlePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_TOTAHandlePtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TgccEventArgs
// Help String      : 
// Default Interface: _gccEventArgs
// Def. Intf. Object: _gccEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TgccEventArgs : public Vcl::Oleserver::TOleServer
{
  _gccEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TgccEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _gccEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_gccEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TToolboxItemEventHandler
// Help String      : 
// Default Interface: _ToolboxItemEventHandler
// Def. Intf. Object: _ToolboxItemEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TToolboxItemEventHandler : public Vcl::Oleserver::TOleServer
{
  _ToolboxItemEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TToolboxItemEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ToolboxItemEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ToolboxItemEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TToolboxItemAddedEventHandler
// Help String      : 
// Default Interface: _ToolboxItemAddedEventHandler
// Def. Intf. Object: _ToolboxItemAddedEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TToolboxItemAddedEventHandler : public Vcl::Oleserver::TOleServer
{
  _ToolboxItemAddedEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TToolboxItemAddedEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ToolboxItemAddedEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ToolboxItemAddedEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TAssemblyUnloadedEventArgs
// Help String      : 
// Default Interface: _AssemblyUnloadedEventArgs
// Def. Intf. Object: _AssemblyUnloadedEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TAssemblyUnloadedEventArgs : public Vcl::Oleserver::TOleServer
{
  _AssemblyUnloadedEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TAssemblyUnloadedEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _AssemblyUnloadedEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_AssemblyUnloadedEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TAssemblyUnloadedEventHandler
// Help String      : 
// Default Interface: _AssemblyUnloadedEventHandler
// Def. Intf. Object: _AssemblyUnloadedEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TAssemblyUnloadedEventHandler : public Vcl::Oleserver::TOleServer
{
  _AssemblyUnloadedEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TAssemblyUnloadedEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _AssemblyUnloadedEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_AssemblyUnloadedEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TMessageGroupEventArgs
// Help String      : 
// Default Interface: _MessageGroupEventArgs
// Def. Intf. Object: _MessageGroupEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TMessageGroupEventArgs : public Vcl::Oleserver::TOleServer
{
  _MessageGroupEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TMessageGroupEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _MessageGroupEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_MessageGroupEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TMessageGroupHandler
// Help String      : 
// Default Interface: _MessageGroupHandler
// Def. Intf. Object: _MessageGroupHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TMessageGroupHandler : public Vcl::Oleserver::TOleServer
{
  _MessageGroupHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TMessageGroupHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _MessageGroupHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_MessageGroupHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TFileNotificationEventArgs
// Help String      : 
// Default Interface: _FileNotificationEventArgs
// Def. Intf. Object: _FileNotificationEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TFileNotificationEventArgs : public Vcl::Oleserver::TOleServer
{
  _FileNotificationEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TFileNotificationEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _FileNotificationEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_FileNotificationEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TBeforeCompileArgs
// Help String      : 
// Default Interface: _BeforeCompileArgs
// Def. Intf. Object: _BeforeCompileArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TBeforeCompileArgs : public Vcl::Oleserver::TOleServer
{
  _BeforeCompileArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TBeforeCompileArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _BeforeCompileArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_BeforeCompileArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TAfterCompileArgs
// Help String      : 
// Default Interface: _AfterCompileArgs
// Def. Intf. Object: _AfterCompileArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TAfterCompileArgs : public Vcl::Oleserver::TOleServer
{
  _AfterCompileArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TAfterCompileArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _AfterCompileArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_AfterCompileArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TFileNotificationHandler
// Help String      : 
// Default Interface: _FileNotificationHandler
// Def. Intf. Object: _FileNotificationHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TFileNotificationHandler : public Vcl::Oleserver::TOleServer
{
  _FileNotificationHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TFileNotificationHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _FileNotificationHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_FileNotificationHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TBeforeCompileHandler
// Help String      : 
// Default Interface: _BeforeCompileHandler
// Def. Intf. Object: _BeforeCompileHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TBeforeCompileHandler : public Vcl::Oleserver::TOleServer
{
  _BeforeCompileHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TBeforeCompileHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _BeforeCompileHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_BeforeCompileHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TAfterCompileHandler
// Help String      : 
// Default Interface: _AfterCompileHandler
// Def. Intf. Object: _AfterCompileHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TAfterCompileHandler : public Vcl::Oleserver::TOleServer
{
  _AfterCompileHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TAfterCompileHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _AfterCompileHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_AfterCompileHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTAContainerTypes
// Help String      : 
// Default Interface: _OTAContainerTypes
// Def. Intf. Object: _OTAContainerTypesPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTAContainerTypes : public Vcl::Oleserver::TOleServer
{
  _OTAContainerTypesPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTAContainerTypes(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTAContainerTypesPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTAContainerTypesPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTADesignerTypes
// Help String      : 
// Default Interface: _OTADesignerTypes
// Def. Intf. Object: _OTADesignerTypesPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTADesignerTypes : public Vcl::Oleserver::TOleServer
{
  _OTADesignerTypesPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTADesignerTypes(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTADesignerTypesPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTADesignerTypesPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTACreatorTypes
// Help String      : 
// Default Interface: _OTACreatorTypes
// Def. Intf. Object: _OTACreatorTypesPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTACreatorTypes : public Vcl::Oleserver::TOleServer
{
  _OTACreatorTypesPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTACreatorTypes(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTACreatorTypesPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTACreatorTypesPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTAIDEPersonalities
// Help String      : 
// Default Interface: _OTAIDEPersonalities
// Def. Intf. Object: _OTAIDEPersonalitiesPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTAIDEPersonalities : public Vcl::Oleserver::TOleServer
{
  _OTAIDEPersonalitiesPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTAIDEPersonalities(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTAIDEPersonalitiesPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTAIDEPersonalitiesPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTAGalleryCategories
// Help String      : 
// Default Interface: _OTAGalleryCategories
// Def. Intf. Object: _OTAGalleryCategoriesPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTAGalleryCategories : public Vcl::Oleserver::TOleServer
{
  _OTAGalleryCategoriesPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTAGalleryCategories(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTAGalleryCategoriesPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTAGalleryCategoriesPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTAFile
// Help String      : 
// Default Interface: _OTAFile
// Def. Intf. Object: _OTAFilePtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TOTAFile : public Vcl::Oleserver::TOleServer
{
  _OTAFilePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTAFile(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTAFilePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTAFilePtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TTOTAGetChildCallback
// Help String      : 
// Default Interface: _TOTAGetChildCallback
// Def. Intf. Object: _TOTAGetChildCallbackPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TTOTAGetChildCallback : public Vcl::Oleserver::TOleServer
{
  _TOTAGetChildCallbackPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TTOTAGetChildCallback(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _TOTAGetChildCallbackPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_TOTAGetChildCallbackPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TComponentRenamedEventArgs
// Help String      : 
// Default Interface: _ComponentRenamedEventArgs
// Def. Intf. Object: _ComponentRenamedEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TComponentRenamedEventArgs : public Vcl::Oleserver::TOleServer
{
  _ComponentRenamedEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TComponentRenamedEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ComponentRenamedEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ComponentRenamedEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TComponentRenamedEventHandler
// Help String      : 
// Default Interface: _ComponentRenamedEventHandler
// Def. Intf. Object: _ComponentRenamedEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TComponentRenamedEventHandler : public Vcl::Oleserver::TOleServer
{
  _ComponentRenamedEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TComponentRenamedEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ComponentRenamedEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ComponentRenamedEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TItemEventArgs
// Help String      : 
// Default Interface: _ItemEventArgs
// Def. Intf. Object: _ItemEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TItemEventArgs : public Vcl::Oleserver::TOleServer
{
  _ItemEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TItemEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ItemEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ItemEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSelectedEventArgs
// Help String      : 
// Default Interface: _SelectedEventArgs
// Def. Intf. Object: _SelectedEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TSelectedEventArgs : public Vcl::Oleserver::TOleServer
{
  _SelectedEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TSelectedEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _SelectedEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_SelectedEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TItemEventHandler
// Help String      : 
// Default Interface: _ItemEventHandler
// Def. Intf. Object: _ItemEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TItemEventHandler : public Vcl::Oleserver::TOleServer
{
  _ItemEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TItemEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ItemEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ItemEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSelectedEventHandler
// Help String      : 
// Default Interface: _SelectedEventHandler
// Def. Intf. Object: _SelectedEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TSelectedEventHandler : public Vcl::Oleserver::TOleServer
{
  _SelectedEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TSelectedEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _SelectedEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_SelectedEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TContextEventArgs
// Help String      : 
// Default Interface: _ContextEventArgs
// Def. Intf. Object: _ContextEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TContextEventArgs : public Vcl::Oleserver::TOleServer
{
  _ContextEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TContextEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ContextEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ContextEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TNodeEventArgs
// Help String      : 
// Default Interface: _NodeEventArgs
// Def. Intf. Object: _NodeEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TNodeEventArgs : public Vcl::Oleserver::TOleServer
{
  _NodeEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TNodeEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _NodeEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_NodeEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TVisibleEventArgs
// Help String      : 
// Default Interface: _VisibleEventArgs
// Def. Intf. Object: _VisibleEventArgsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TVisibleEventArgs : public Vcl::Oleserver::TOleServer
{
  _VisibleEventArgsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TVisibleEventArgs(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _VisibleEventArgsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_VisibleEventArgsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTAStructureType
// Help String      : 
// Default Interface: _OTAStructureType
// Def. Intf. Object: _OTAStructureTypePtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTAStructureType : public Vcl::Oleserver::TOleServer
{
  _OTAStructureTypePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTAStructureType(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTAStructureTypePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTAStructureTypePtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTANodeType
// Help String      : 
// Default Interface: _OTANodeType
// Def. Intf. Object: _OTANodeTypePtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTANodeType : public Vcl::Oleserver::TOleServer
{
  _OTANodeTypePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTANodeType(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTANodeTypePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTANodeTypePtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOTAStructureViewOptions
// Help String      : 
// Default Interface: _OTAStructureViewOptions
// Def. Intf. Object: _OTAStructureViewOptionsPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOTAStructureViewOptions : public Vcl::Oleserver::TOleServer
{
  _OTAStructureViewOptionsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOTAStructureViewOptions(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _OTAStructureViewOptionsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_OTAStructureViewOptionsPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TContextEventHandler
// Help String      : 
// Default Interface: _ContextEventHandler
// Def. Intf. Object: _ContextEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TContextEventHandler : public Vcl::Oleserver::TOleServer
{
  _ContextEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TContextEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _ContextEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ContextEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TNodeEventHandler
// Help String      : 
// Default Interface: _NodeEventHandler
// Def. Intf. Object: _NodeEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TNodeEventHandler : public Vcl::Oleserver::TOleServer
{
  _NodeEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TNodeEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _NodeEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_NodeEventHandlerPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TVisibleEventHandler
// Help String      : 
// Default Interface: _VisibleEventHandler
// Def. Intf. Object: _VisibleEventHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (0)
// *********************************************************************//
class PACKAGE TVisibleEventHandler : public Vcl::Oleserver::TOleServer
{
  _VisibleEventHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TVisibleEventHandler(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  _VisibleEventHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_VisibleEventHandlerPtr intf);


};

};     // namespace Borland_studio_toolsapi_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Borland_studio_toolsapi_tlb;
#endif

#pragma pack(pop)
#pragma option pop

#endif // Borland_Studio_ToolsAPI_OCXH
